version: '2.1'

services:
  getir-case-study:
    image: getir-case-study
    container_name: getir-case-study
    build: .
    environment:
      NODE_ENV: development
      PORT: "3000"
      Mongo: mongodb://dbUser:dbPassword1@ds249623.mlab.com:49623/getir-case-study
    ports:
      - 3000:3000
      - "9200:9200"
    networks: 
      - getir

networks:
  getir:
    external: true 